### PR TITLE
gstlal-burst v0.3.0

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
This is not ready, mainly because we haven't merged conda-forge/gstlal-ugly-feedstock#4 yet (I thought we had, and I have a local copy).

**Comment by myNameIsPatrick** [comment]
Thanks @duncanmmacleod, this looks good. I'll look into getting your workarounds/issues fixed for a future point release.

**Comment by duncanmmacleod** [comment]
@myNameIsPatrick, the tests are failing on macOS only as follows:

```
+ gstlal_snax_extract --help
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/gstlal-burst_1612426296564/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/gstlal_snax_extract", line 84, in <module>
    setrlimit(resource.RLIMIT_STACK, 1024 * 1024)  # 1 MiB per thread
  File "/Users/runner/miniforge3/conda-bld/gstlal-burst_1612426296564/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/gstlal_snax_extract", line 72, in setrlimit
    resource.setrlimit(res, (lim if lim is not None else hard_lim, hard_lim))
ValueError: current limit exceeds maximum limit
```

Please advise.

**Review by myNameIsPatrick — APPROVED** [review]
Looks good @duncanmmacleod, thanks for pushing through on this and adding in the macOS patch.

**Pull request merged**
